apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
            {
                "resourceName": "mlxnics",
                "selectors": [{
                    "vendors": ["15b3"],
                    "devices": ["101d"],
                    "drivers": ["mlx5_core"],
                    "vdpaType": "vhost"
                }]
            }
        ]
    }
