apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: netbindingvdpa
spec:
  config: '{
            "cniVersion": "1.0.0",
            "name": "netbindingvdpa",
            "plugins": [
              {
                "type": "cni-vdpa-binding-plugin"
              }
            ]
  }'
