apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vdpa-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: kubevirt.io/sriov_net
spec:
  config: '{"cniVersion":"0.3.1","name":"vdpa-network","type":"sriov","ipam":{},"dns":{}}'
