---
apiVersion: v1
kind: Pod
metadata:
  name: debug-network-1
  annotations:
    v1.multus-cni.io/default-network: ovn-kubernetes-a

spec:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    resources:
      requests:
        openshift.io/mlxnics: '1'
      limits:
        openshift.io/mlxnics: '1'
    command:
      - sleep
      - "3600"
  imagePullSecrets:
    - name: rh-ee-lmilleri-pull-secret
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations

---
apiVersion: v1
kind: Pod
metadata:
  name: debug-network-2
  annotations:
    v1.multus-cni.io/default-network: ovn-kubernetes-b

spec:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    resources:
      requests:
        openshift.io/mlxnics: '1'
      limits:
        openshift.io/mlxnics: '1'
    command:
      - sleep
      - "3600"
  imagePullSecrets:
    - name: rh-ee-lmilleri-pull-secret
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations

