---
apiVersion: v1
kind: Pod
metadata:
  name: debug-network-1
  namespace: openshift-sriov-network-operator
  annotations:
    v1.multus-cni.io/default-network: kube-system/ovn-kubernetes-a

spec:
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: Always
    #securityContext:
      #capabilities:
        #drop: ["ALL"]
      #allowPrivilegeEscalation: false
      #runAsNonRoot: true
      #seccompProfile:
        #type: "RuntimeDefault"
      #privileged: false
    securityContext:
      privileged: true
    command:
      - sleep
      - "3600"
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-network-2
  namespace: openshift-sriov-network-operator
  annotations:
    v1.multus-cni.io/default-network: kube-system/ovn-kubernetes-a

spec:
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: Always
    #securityContext:
      #capabilities:
        #drop: ["ALL"]
      #allowPrivilegeEscalation: false
      #runAsNonRoot: true
      #seccompProfile:
        #type: "RuntimeDefault"
      #privileged: false
    securityContext:
      privileged: true
    command:
      - sleep
      - "3600"
