apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod2
  namespace: vdpa
  annotations:
    v1.multus-cni.io/default-network: kube-system/ovn-kubernetes-sriov
spec:
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command:
      - sleep
      - "3600"
