apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-kubernetes-sriov
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/mlxnicssriov
spec:
  config: '{"cniVersion":"0.3.1","name":"ovn-kubernetes-sriov","type":"ovn-k8s-cni-overlay","ipam":{},"dns":{}}'
