apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-kubernetes-a
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/mlxnics
spec:
  config: '{ "cniVersion": "0.3.1", "name": "l2-network", "type": "ovn-k8s-cni-overlay", "capabilities" : {"CNIDeviceInfoFile": true}, "topology":"layer2", "subnets": "10.100.200.0/24", "mtu": 1300, "netAttachDefName": "vdpa/ovn-kubernetes-a", "excludeSubnets": "10.100.200.0/29" }'
