apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-network
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/mlxnics
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "ovs",
      "bridge": "vdpa-br",
      "vlan": 100,
      "ipam": {
        "type": "static"
      }
    }'
