apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-kubernetes-b
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/mlxnicsvirtio
spec:
  config: |2 
      { "cniVersion": "0.3.1", 
        "name": "l2-network", 
        "type": "ovn-k8s-cni-overlay", 
        "capabilities" : {"CNIDeviceInfoFile": true}, 
        "topology":"localnet", 
        "subnets": "10.100.200.0/24", 
        "mtu": 1300, 
        "netAttachDefName": "vdpa/ovn-kubernetes-b", 
        "excludeSubnets": "10.100.200.0/29" 
      }
