apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vdpa-network-711
spec:
  nodeSelector:
    kubernetes.io/hostname: virtlab711.virt.lab.eng.bos.redhat.com
  desiredState:
    interfaces:
      - name: vdpa-br
        description: vdpa ovs bridge
        type: ovs-bridge
        state: up
        bridge:
          allow-extra-patch-ports: true
          options:
            stp: true
          port:
            - name: ens1f0
    ovn:
      bridge-mappings:
      - bridge: vdpa-br
        localnet: l2-network
        state: present
        #state: ignore
    ovs-db:
      external_ids:
        dumb-thing-you-need-todo-because: OCPBUGS-18869
