apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod1
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "ovs-network",
          "ips": ["10.10.10.1/24"],
          "interface": "---0126789012"
        }
    ]'
spec:
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
