apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod1
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/networks: vdpa/ovn-kubernetes-b
spec:
  nodeSelector:
    region: "711"
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:latest
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
