apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod711
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/networks: vdpa/ovn-kubernetes-a
spec:
  nodeSelector:
    region: "711"

  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:dpdk-latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      limits:
        memory: "8Gi"
        cpu: "16"
        hugepages-1Gi: "6Gi"
      requests:
        memory: "8Gi"
        cpu: "16"
        hugepages-1Gi: "6Gi"
    command: ["sleep", "infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
