apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod4
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/networks: vdpa/ovn-kubernetes-a
spec:
  containers:
  - name: debug-network-pod
    image: quay.io/rh_ee_lmilleri/alpine:dpdk
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "2"
        hugepages-1Gi: "3Gi"
      requests:
        memory: "1Gi"
        cpu: "2"
        hugepages-1Gi: "3Gi"
    command: ["sleep", "infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
